substitutions:
  status_three_way_valve: Vanne 3-voies
  status_three_way_valve_2: Vanne 3-voies no 2
  heatpump_climate_dhw: Thermostat ECS
  dhw_temp: Temp actuelle ECS
  dhw_secondary_temp: Temp ECS secondaire
  status_dhw_forced: ECS Forcé
  dhw_flow_temp_drop: Baisse temp max ECS
  status_prohibit_dhw: ECS interdit
  dhw_flow_temp_target: Consigne ECS
  status_dhw_eco: ECS Eco
  esp_ip: ESP IP
  internal_esp_temperature: Temp interne ESP
  esp_sidd: ESP SSID
  uptime: ESP Uptime
  esp_version: ESP Version
  restart_button: ESP Restart
  status_in1_request: Thermostat Z1 (IN1)
  status_in6_request: Thermostat Z2 (IN6)
  status_in5_request: Thermostat Ext (IN5)
  heatpump_select_dhw_mode: Mode ECS
  normal: Normal
  eco: Eco
  version: ESP Version
  led_brightness: Luminosité LED
  led_switch: LED
  heatpump_switch_force_dhw: Forcer ECS
  heatpump_switch_power_mode: Pompe à chaleur
  heatpump_switch_holiday: Mode vacances
  wifi_signal_proc: Signal Wifi %
  wifi_signal_db: Signal Wifi dB
  z1_flow_temp_target: Consigne Temp d'eau Zone 1
  status_prohibit_cool_z1: Zone 1 Clim Interdite
  status_prohibit_heating_z1: Zone 1 Chauffage Interdit
  heatpump_climate_z1: Thermostat Zone 1
  heatpump_climate_room_z1: Température Zone 1
  z1_room_temp_target: Z1 Temp cible pièce
  z1_room_temp: Z1 Temp pièce
  heatpump_number_z2_set_flow_temperature: Temp cible Zone 2 C/F
  z2_flow_temp_target: Consigne Temp d'eau Zone 2
  status_prohibit_cool_z2: Zone 2 Clim Interdite
  status_prohibit_heating_z2: Zone 2 Chauffage Interdit
  heatpump_number_z2_set_room_temperature: Z2 Temp cible pièce
  heatpump_climate_z2: Thermostat Zone 2
  heatpump_climate_room_z2: Température Zone 2
  z2_room_temp_target: Z2 Temp cible pièce
  z2_room_temp: Z2 Temp pièce
  mixing_tank_temp: Température du tampon
  boiler_flow_temp: Temp départ chaudière
  boiler_return_temp: Temp retour chaudière
  status_booster: Statut réchauffeur élec
  compressor_frequency: Freq Compresseur
  controller_version_text: Version Controleur
  controller_firmware_text: Firmware Controleur
  controller_datetime_text: Date du Controleur
  cool_consumed: Conso Clim
  cool_cop: COP Clim
  cool_delivered: Energ Délivrée Clim
  status_defrost: Dégivrage
  dhw_consumed: Conso ECS
  dhw_cop: COP ECS
  dhw_delivered: Energ Délivrée ECS
  hp_feed_temp: Temp départ Primaire
  z1_feed_temp: Z1 Temp départ
  z2_feed_temp: Z2 Temp départ
  flow_rate: Débit
  heat_source_text: Source de chaleur
  heatpump: Pompe à chaleur
  immersion_heater: Thermoplongeur
  booster_heater: Résistances électrique
  immersion_and_booster_heater: Thermoplongeur et Réchauffeur électrique
  boiler: chaudière
  energy_consumed_increasing: Énergie Totale Consommée
  heating_consumed: Conso chauffage
  heating_cop: COP Chauffage
  heating_delivered: Energ Délivrée Chauffage
  status_holiday: Mode Vacances
  status_immersion: Thermoplongeur
  legionella_prevention_temp: Temp Prévention Légionelle
  heatpump_select_operating_mode: Mode sélectionné
  heat_target_temperature: Temp cible Chauffage
  heat_flow_temperature: Temp eau départ chauffage
  heat_compensation_curve: Courbe de compensation
  cool_target_temperature: Temp cible Clim
  cool_flow_temperature: Temp eau départ clim
  operation_off: "Off"
  hotwater: Eau chaude
  heating: Chauffage
  cooling: Rafraichissement
  frost_protection: Protection contre le givre
  legionella_prevention: Prévention Légionelle
  runtime: Durée de fonctionnement
  status_operation: Mode de fonctionnement
  output_power: Puissance Délivrée
  computed_output_power: Puissance Délivrée estimée
  computed_cop: COP estimée
  daily_computed_output_power: Puissance de sortie estimée (Tous les jours)
  daily_repported_input_power: Consommation totale d'énergie quotidienne déclarée
  outside_temp: Temp Ext
  hp_refrigerant_temp: Temp Réfrigérant
  hp_refrigerant_condensing_temp: Temp de Condensation
  hp_return_temp: Temp retour Primaire
  z1_return_temp: Z1 Temp retour
  z2_return_temp: Z2 Temp retour
  status_water_pump: Circulateur primaire
  status_water_pump_2: Circulateur Zone 1
  status_water_pump_3: Circulateur Zone 2
  status_mixing_valve: Statut Vanne de Mélange
  mixing_valve_step: Position Vanne de Mélange
  status_multi_zone: Multizone Statut
  status_multi_zone_idle: Inactif
  status_multi_zone_both: Les deux
  status_multi_zone_zone1: Z1 fonctionne
  status_multi_zone_zone2: Z2 fonctionne
  fault_code_text: Code erreur
  refrigerant_error_code_text: Code erreur Frigo
  compressor_starts: Nb Démarrages compresseur
  discharge_temp: Température de refoulement
  ou_liquid_pipe_temp: Température du tuyau de liquide 1 de l'unité extérieure
  ou_two_phase_pipe_temp: Température du tuyau biphasé de l'unité extérieure
  fan_speed: Vitesse du ventilateur
  ou_suction_pipe_temp: Outside Unit Suction Pipe Temp
  ou_heatsink_temp: Outside Unit Heatsink Temp
  super_heat_temp: Discharge Superheat Temp
  sub_cool_temp: Subcooling Temp
